os: linux
dist: xenial

sudo: required

language: python
python:
  - "3.6"

branches:
  only:
    - master

install:
  - set -o errexit; source .travis/test_01_install.sh
script:
  - set -o errexit; source .travis/test_02_script.sh

cache:
  pip: true
