os: linux
dist: xenial

language: python
python:
  - "3.6"

branches:
  only:
    - master

before_install:
  - set -o errexit; source .travis/00_before_install.sh
install:
  - set -o errexit; source .travis/01_install.sh
script:
  - set -o errexit; source .travis/02_script.sh

cache:
  pip: true
